CREATE TABLE users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE tags (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(255) NOT NULL,
    color   VARCHAR(255) DEFAULT '#6B7280',
    user_id BIGINT
);

CREATE TABLE todos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(255) NOT NULL,
    description     VARCHAR(255),
    completed       BOOLEAN      NOT NULL DEFAULT FALSE,
    priority        VARCHAR(255)          DEFAULT 'MEDIUM',
    created_at      TIMESTAMP,
    start_at        TIMESTAMP,
    due_at          TIMESTAMP,
    deleted_at      TIMESTAMP,
    user_id         BIGINT,
    parent_id       BIGINT,
    recurrence_rule VARCHAR(255),
    missed_count    INT          NOT NULL DEFAULT 0,
    recurrence_days INT          NOT NULL DEFAULT 0
);

CREATE TABLE todo_tags (
    todo_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL,
    PRIMARY KEY (todo_id, tag_id),
    CONSTRAINT fk_todo_tags_todo FOREIGN KEY (todo_id) REFERENCES todos (id),
    CONSTRAINT fk_todo_tags_tag  FOREIGN KEY (tag_id)  REFERENCES tags (id)
);
